# Generated by Django 5.1.3 on 2024-11-28 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tree_manager.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incoming_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='tree_manager.treenode')),
                ('outgoing_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='tree_manager.treenode')),
            ],
        ),
        migrations.CreateModel(
            name='TreeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='tree_manager.treeversion')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tree_manager.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeNodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tree_manager.treenode')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_versions', to='tree_manager.treeversion')),
            ],
        ),
        migrations.CreateModel(
            name='TreeEdgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tree_manager.treeedge')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_versions', to='tree_manager.treeversion')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tree_manager.tree')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='tree_manager.treeversion')),
            ],
        ),
    ]
